name: CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push product-service
      uses: docker/build-push-action@v4
      with:
        context: ./product-service
        tags: vishnususilkumar/product-service:latest
        push: true

    - name: Build and push inventory-service
      uses: docker/build-push-action@v4
      with:
        context: ./inventory-service
        tags: vishnususilkumar/inventory-service:latest
        push: true

    - name: Build and push client-service
      uses: docker/build-push-action@v4
      with:
        context: ./client-service
        tags: vishnususilkumar/client-service:latest
        push: true

  test:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Install dependencies for product-service
      run: |
        cd product-service
        npm install

    - name: Run tests for product-service
      run: |
        cd product-service
        npm test

    - name: Install dependencies for inventory-service
      run: |
        cd inventory-service
        npm install

    - name: Run tests for inventory-service
      run: |
        cd inventory-service
        npm test

    - name: Install dependencies for client-service
      run: |
        cd client-service
        npm install

    - name: Run tests for client-service
      run: |
        cd client-service
        npm test

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Deploy with Docker Compose
      run: docker-compose up
